### ISSUE TITLE
How to play the Extreme Version ?

### ISSUE THREAD

**Issue by Catarax** [jorio/Nanosaur#1]
Hello, 
I can't find a way to play the extreme version on windows, thank you !

**Comment by jorio** [comment]
Hi! There’s a performance issue that impacts Extreme a bit too much at the moment, so I haven’t made Extreme available in the builds yet. When I get around to fixing this, I’ll make new builds that let you play Extreme :)

If you want to modify the game to try out Extreme anyway, you can replace the following `#if 0` by an `#if 1` here (Note that Extreme is actually referred to as "pro mode" in the code): https://github.com/jorio/Nanosaur/blob/1f9a40bfd4d096b4ef9225c63cd0c19b7eaf46e3/src/Main.cpp#L139

**Comment by jorio** [comment]
Extreme is available in v1.4.1!
