### ISSUE TITLE
Failed to build on Raspberry Pi 2 (RaspberryPi OS / ARM 32bit)

### ISSUE THREAD

**Issue by github-userx** [jorio/Nanosaur#12]
```
pi@raspberrypi:~/Desktop/Nanosaur $ cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
-- Found SDL2: /usr/include/SDL2  
-- Found SDL2: /usr/include/SDL2  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Desktop/Nanosaur/build
```

```
pi@raspberrypi:~/Desktop/Nanosaur $ cmake --build build
[  1%] Building CXX object extern/Pomme/CMakeFiles/Pomme.dir/src/PommeDebug.cpp.o
/home/pi/Desktop/Nanosaur/extern/Pomme/src/PommeDebug.cpp: In function ‘std::__cxx11::string Pomme::FourCCString(uint32_t, char)’:
/home/pi/Desktop/Nanosaur/extern/Pomme/src/PommeDebug.cpp:47:7: error: ‘reverse’ is not a member of ‘std’
  std::reverse(b, b + 4);
       ^~~~~~~
make[2]: *** [extern/Pomme/CMakeFiles/Pomme.dir/build.make:76: extern/Pomme/CMakeFiles/Pomme.dir/src/PommeDebug.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:123: extern/Pomme/CMakeFiles/Pomme.dir/all] Fehler 2
make: *** [Makefile:84: all] Fehler 2
pi@raspberrypi:~/Desktop/Nanosaur $
```

(„Fehler“ means „Error“..my operating language is German). I did successfully install libsdl2-dev.

**Comment by jorio** [comment]
Can you clone the game (recursively) on branch "[devel](https://github.com/jorio/Nanosaur/tree/devel)" and try building again? This branch includes fixes for old versions of GCC. Let me know if it works!

**Comment by github-userx** [comment]
@jorio Using the devel branch for building worked perfectly and Nanosaur runs smooth on RaspberryPi 2 using the FullKMS OpenGL driver (enabled via: sudo raspi-config).

This could be huge for RaspberryPi Gaming and bringing these games to a new young audience.  Depending on how the thing with the Debian/Ubuntu repositories and the licensing of the ported games goes, I could even imagine working with the RaspberryPi Foundation to ship „RaspberryPi OS“ with these games (if I remember correctly the full raspberrypiOS version already has a free version of Minecraft included for example)

**Comment by jorio** [comment]
Great! Closing the issue because I merged the fix into the master branch.

---
Re: bundling the games with the Raspberry Pi — that's a great idea.

I think Bugdom would be a great candidate. Bugdom might be a little slow on a Pi right now but I'm currently rewriting its rendering code like I did with Nanosaur 1.4.2; it should be smoother when I'm done. I don't have a Pi though so maybe it just runs fine.

Let me know if you need help with this, I'd be happy to help make it happen.
Maybe you should pitch the idea to Pangea too?

**Comment by github-userx** [comment]
awesome! Have you seen my issue regarding building bugdom?

**Comment by jorio** [comment]
Yes, I’ll look into fixing the Bugdom compilation issue when I have some free time. Nanosaur was the easier game to fix so I did that one first ;)

**Comment by github-userx** [comment]
Okay, thank you so much! No worries or hurries! :)

**Comment by CoWinkKeyDinkInc** [comment]
I have tried this with a Raspberry Pi 3 following @github-userx's advice with the FullKMS driver and it preforms well. The frame rate is playable but seems to be a bit low considering the CPU usage doesn't go above 20-25%.
