### ISSUE TITLE
Getting Nanosaur packaged for the official Debian/Ubuntu repositories 

### ISSUE THREAD

**Issue by github-userx** [jorio/Nanosaur#13]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=989523

**Comment by jserv** [comment]
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=989523

I thought the subject of the submitted Debian package was misleading -- `Nanosaur` is not an open source project by definition. Pangea Software released the source code with [notable restrictions](http://www.pangeasoft.net/nano/nanosource.html):
1. YOU CANNOT post or mass distribute modified versions of Nanosaur which you have created.
2. YOU CANNOT use more than 1000 lines of this code in your own applications without purchasing a game engine license from Pangea Software.
3. YOU CANNOT  get any technical support on this code from Pangea Software. Technical support is only available to paid licensees of the code.
4. YOU CANNOT  port any of this code in any quantity, shape or form to Windows/PC. Nanosaur and the code are happily Mac-only and we want to keep it that way.

**Comment by github-userx** [comment]
I guess I’d have to reach out to Brian Greenstone about this. The last point isn’t even true anymore with Nanosaur staying „Mac only code“, correct?

**Comment by jserv** [comment]
> I guess I’d have to reach out to Brian Greenstone about this. The last point isn’t even true anymore with Nanosaur staying „Mac only code“, correct?

Besides the above licensing terms by Pangea Software, I would like to ask @jorio for making list of the grant documents negotiated between each other. Otherwise, there are obviously incompatibilities for this project.

**Comment by jorio** [comment]
﻿I’ve just asked Brian. I’ll let you guys know once we’ve clarified this.

**Comment by jpenguin** [comment]
As far as I know, Debian won't accept anything with a NonComercial license https://www.debian.org/social_contract#guidelines

If anyone can write the scripts required to build deb files, I welcome any help.  I have x86_64 & aarch64 appimages generated here
https://build.opensuse.org/project/show/home:jpenguin:Games

**Comment by khumba** [comment]
These games bring back incredible nostalgia for me.  Huge thanks to Pangea Software, @jorio, and the other porters.

If it's worth anything, Pangea does link to these repos from their website, which doesn't confirm their licenses but at least endorses their existence:

> http://www.pangeasoft.net/nano/files.html:
> An OS X version is now available as OpenSource on GitHub. Both the code and actual game are now available for OS and PC.
> 
> http://www.pangeasoft.net/bug/register.html:
> A fan by the name of Iliyas Jorio has taken the Open Source Bugdom source code and managed to create a new version that will work on Mac OS X and 11! You can download it for free here:
> 
> http://www.pangeasoft.net/mightymike/download.html:
> Mighty Mike has been updated for Mac OS X and 11, and also Windows!
Special thanks to our super-fan Iliyas Jorio who made this happen!

Waiting patiently so that I can provide unofficial packaging for Gentoo as well.

**Comment by jpenguin** [comment]
It's not recommended to use CC licenses for code https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software
NC is definitely not DFSG compatible though https://wiki.debian.org/DFSGLicenses

**Comment by github-userx** [comment]
Ah damn i feared something like this

**Comment by jpenguin** [comment]
There's no licensing requirements in the OBS though, I have RPMs & appimages- if you know debian packaging, please help me  https://build.opensuse.org/project/show/home:jpenguin:Games

**Comment by foote-darrell** [comment]
>  https://build.opensuse.org/project/show/home:jpenguin:Games
@ jpenguin seems like a dead link.

**Comment by jpenguin** [comment]
> >  https://build.opensuse.org/project/show/home:jpenguin:Games
> 
> @jpenguin seems like a dead link.
> 
> 

Since jorio started officially providing appimages, I have seen no need to keep up my repository.  Either download the appimage from here, use lutris or use itch.io

**Comment by jorio** [comment]
Closing this issue because it's unlikely that Debian will ever package the game. The license doesn't meet the stringent requirements for "free software". As @jpenguin said, though, there are other great choices for running the game on Linux now: you can use my official AppImage builds or the Flatpak.
