### ISSUE TITLE
Integer underflow causes enemies to go north on Fedora arm64

### ISSUE THREAD

**Issue by orazioedoardo** [jorio/Nanosaur#14]
I've tried to compile Nanosaur on Fedora ARM64 using your instructions. It worked though I immediately noticed that enemy dinosaurs did not walk towards the player but went north, towards z = 0. Also the portal compass most of the times (1) pointed towards north too.

![window](https://user-images.githubusercontent.com/22700499/131216839-7ab7f267-f9bb-464d-a757-680c42ac38e9.png)

Upon inspection, I've figured out that enemies find the player using [this](https://github.com/jorio/Nanosaur/blob/6aab60bcda1065b6a5046c3627c2cc0a387efc8e/src/QD3D/3DMath.c#L62-L69) function. It calculates how much `from` has to steer to go to `to`. It uses [atan2](https://en.cppreference.com/w/cpp/numeric/math/atan2) which returns a value from -pi to +pi. Before passing to [MaskAngle](https://github.com/jorio/Nanosaur/blob/6aab60bcda1065b6a5046c3627c2cc0a387efc8e/src/QD3D/3DMath.c#L134-L143) it subtracts pi/2, which changes the input range (angle) to [pi/2, -3pi/2] (2). The issue here is that MaskAngle applies a conversion using `unsigned short`, but angle can be negative and multiplying unsigned by float is undefined behavior as far as I can tell, so I guess it's up to the compiler.

On x86_64 Linux it looks like the negative float is simply wrapped around the max value, so it's still underflow but then it's masked against 0xffff, which fixes the "issue". On arm64 though, when angle is negative, the multiplication is always 0 for 3/4 (1) of the unit circle (2), from 0 to -3/2pi. Fix was simple, just replace `unsigned short` with `int16_t` to allow negatives.

**Comment by jorio** [comment]
Wow! Nice find. Thank you for the detailed investigation. I'll push a fix soon. What compiler are you using?

This doesn't affect the current ARM64 macOS build, does it? I think I recall you testing the game on that platform earlier. (Still don't have actual ASi hardware to test that myself, unfortunately.)

**Comment by orazioedoardo** [comment]
```
$ gcc --version
gcc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)
```

I can't test (or build) on AS right now, though I'm sure the old build from tag 1.4.2 did work fine when built using the Xcode project. I wonder why.

**Comment by jorio** [comment]
It looks like gcc emits `fcvtzu` for a float-to-u16 cast, whereas clang emits `fcvtzs` at -O1 and up. That would explain why the Mac build happens to work (it's compiled with clang).

**Comment by jorio** [comment]
Fixed. Thank you for investigating this!
