### ISSUE TITLE
Clarify "Port philosophy" paragraph of readme

### ISSUE THREAD

**Issue by cooljeanius** [jorio/Nanosaur#16]
(oops, I submitted too soon originally; editing in what I originally intended to type up...)
When the Readme file says, "I aimed to accurately maintain the behavior of the original game," does that include behaviors that were in the original game that probably would have been considered bugs if they'd been noticed at the time? Like, is the aim [bug-for-bug compatibility](http://www.catb.org/jargon/html/B/bug-for-bug-compatible.html), or can old bugs be fixed? Where does the line fall between "minor quality-of-life improvements" and "modifications to the gameplay or presentation" that would be "out of the scope of this project"?
https://github.com/jorio/Nanosaur/blob/d19076b2783c80e7b67d046bf23e966b1140e41f/README.md?plain=1#L22-L29

**Comment by jorio** [comment]
I just updated the readme.

Yes, it's pretty much the same idea for Bugdom. When I first got it to run, the physics were completely out of whack (similar to the old Windows port by IFD, in fact). Instead of aiming for perfect accuracy, I decided to go ahead and fix it until the game felt good to play and behaved close enough to the OS 9 version.

**Comment by cooljeanius** [comment]
> I just updated the readme.
> 
> Yes, it's pretty much the same idea for Bugdom. When I first got it to run, the physics were completely out of whack (similar to the old Windows port by IFD, in fact). Instead of aiming for perfect accuracy, I decided to go ahead and fix it until the game felt good to play and behaved close enough to the OS 9 version.

How much of this Bugdom speedrun would you say is based on ~~bugs...~~ er, I mean, *glitches*, vs. intended behavior? https://www.speedrun.com/bd/run/y81xvwnz

**Comment by coolkirby2000** [comment]
> How much of this Bugdom speedrun would you say is based on ~bugs...~ er, I mean, _glitches_, vs. intended behavior?
Note that all those speedruns are done on IFD's PC port from 2003. This port introduced all the game-breaking physics glitches like roll boost. Because they are porting bugs, the original Mac version that jorio is fixing up doesn't have those oddities.

**Comment by coolkirby2000** [comment]
> How much of this Bugdom speedrun would you say is based on ~bugs...~ er, I mean, _glitches_, vs. intended behavior?

Note that all those speedruns are done on IFD's PC port from 2003. This port introduced all the game-breaking physics glitches like roll boost. Because they are porting bugs, the original Mac version that jorio is fixing up doesn't have those oddities.
