### ISSUE TITLE
No signing and notarization

### ISSUE THREAD

**Issue by Theile** [jorio/Nanosaur#17]
Bugdom has that, and it would be nice for all titles to be secured with this.

**Comment by jorio** [comment]
I've finally set up a CI pipeline for Nanosaur that codesigns and notarizes macOS builds. I'll mark this issue as resolved next time I put out a release.

**Comment by Theile** [comment]
Thank you!

I have added the signed games as labels in our [Installomator](https://github.com/Installomator/Installomator/). But am missing this one…

**Comment by jorio** [comment]
@Theile, [Nanosaur 1.4.3](https://github.com/jorio/Nanosaur/releases/tag/v1.4.3) is signed.

I'll take care of the last game shortly (Mighty Mike).

**Comment by Theile** [comment]
Great, thanks!
