### ISSUE TITLE
Stuttering FPS on M1 Macs

### ISSUE THREAD

**Issue by sxflynn** [jorio/Nanosaur#18]
I played this Nanosaur build on a 13" 2013 Macbook Pro Retina  and the frame rate is buttery smooth. However I opened this on my new M1 Mac Mini which is connected to a 2560x1440 display (identical resolution) and the frame rate is smooth, but also suffers from some jitters.

Edit: I should add that my 2013 MBP is running Mojave.

**Comment by sxflynn** [comment]
Ok I do want to apologize because all I did was change the setting to have V-Sync be OFF and now it plays at a good FPS with no noticeable stuttering. I have my M1 Mac Mini connected to the same 27" Dell 2560x1440 display that I did for the 13" Macbook Pro so I don't know why this new setup has different performance.

**Comment by jorio** [comment]
[macOS Monterey appears to break v-sync in OpenGL applications.](https://github.com/libsdl-org/SDL/issues/4918) Several other games seem to be affected by this problem.

For now I'd like to hold out a bit in the hope that an OS update fixes this; if not, I'll implement a workaround eventually.

In the meantime, you can turn off v-sync, as you found out.

**Comment by sxflynn** [comment]
Thanks for your work on this project!

**Comment by jorio** [comment]
@sxflynn, macOS update 12.1 just came out and it looks like it fixes vsync issues.
