### ISSUE TITLE
Can controls be reconfigured?

### ISSUE THREAD

**Issue by ScarletSwordfish** [jorio/Nanosaur#2]
Can controls be reconfigured? I remember one version of the game had a control configuration dialog.

**Comment by jorio** [comment]
You're right, the original game had a control remapping dialog provided by InputSprockets, but I haven't had time to recreate that part yet. I'd like to add gamepad support as well. Stay tuned!

**Comment by jorio** [comment]
[Version 1.4.2](https://github.com/jorio/Nanosaur/releases/tag/v1.4.2) lets you remap keyboard controls in the settings screen!

**Comment by github-userx** [comment]
@jorio what does basic gamepad support mean? Possible to maybe play Nanosaur or Bugdom with Xbox controller (usb)?

**Comment by jorio** [comment]
Bug, Nano and Mike are all already playable with a gamepad.

What I meant with "basic" in the release notes is that the controls are hardcoded into the game. I haven't written a config screen for gamepad controls.

If the game won't let you use your gamepad, then it's probably a driver issue. On Linux in particular, you may have better luck with [xboxdrv](https://wiki.archlinux.org/title/Gamepad#Xbox_360_controller).

**Comment by github-userx** [comment]
I hereby can confirm that Nanosaur works without issues on Windows10 with a Xbox360 usb Controller. 

Bugdom (noquesa branch/July 4 2021) also works with the controller on Ubuntu-Mate 20.04 without having to configure anything or having to install any additional driver(s) or software. I haven’t tried Nanosaur with controller on Ubuntu-Mate yet but It should work as well.
