### ISSUE TITLE
Any way to change Windowed/Fullscreen resolutions via a menu option?

### ISSUE THREAD

**Issue by eisnerguy1** [jorio/Nanosaur#25]
I was wondering if there was any way to change the resolution of the game via a menu option? I know that there is the "--fullscreen-resolution WIDTH HEIGH" command line option but, there's no option to change the resolution while in Windowed mode. Ideally, I'd love an option to have the game's resolution as 1280x960/2x scaled. Or, if that can't be done, maybe include a command line option for "--windowed-resolution WIDTH HEIGH" and also include 1280x960 as a valid option?

My main issue is that the UI just stretches while in Fullscreen mode.

Here's Windowed mode:
<img width="640" alt="Nanosaur_Windowed" src="https://user-images.githubusercontent.com/3295271/170895106-3692d095-1053-49b8-9ad4-14f5313d8836.png">

And then Fullscreen mode:
![Nanosaur_Fullscreen](https://user-images.githubusercontent.com/3295271/170895109-e7b53c72-05f8-41fc-b9a3-e9c08fccdc53.png)

Thanks!

**Comment by jorio** [comment]
In [Nanosaur 1.4.4](https://github.com/jorio/Nanosaur/releases/tag/v1.4.4), try "Aspect Ratio: Force 4:3" in the settings :)
