### ISSUE TITLE
I get the following picture issue about Assertion fail over _GLDrawRangeEllements

### ISSUE THREAD

**Issue by Rasagiel** [jorio/Nanosaur#30]
Hello, so I downloaded first time the 1.4.3 version for Windows, first session run smoothly well but now I come back it and I am having this error pop up. What can I do please?
![Καταγραφή](https://user-images.githubusercontent.com/113258542/189495958-8e72cd00-a087-4b57-a41d-36d14338ba44.PNG)

**Comment by jorio** [comment]
[Nanosaur 1.4.4](https://github.com/jorio/Nanosaur/releases/tag/v1.4.4) doesn't use glDrawRangeElements anymore. Feel free to reopen the issue if it still crashes for you.
