### ISSUE TITLE
On screen map is in the way on widescreen displays

### ISSUE THREAD

**Issue by orazioedoardo** [jorio/Nanosaur#33]
Since it looks like you are doing batch updates on Pangea games, could you move the map so that it stays locked to the right even when the window is resized? Currently the map looks like [this](https://youtu.be/rRf0A5VDa38?t=278) on widescreen displays. In my fork I've just lazily [changed coordinates](https://github.com/orazioedoardo/Nanosaur/blob/fd597fcae7836351ca882ce4d4ef7c62725c01cc/src/Screens/Infobar.c#L647-L648), however that moves the map off screen on 4:3 aspect ratio. An option to change HUD proportion so that it's not stretched would be welcome too.

![screen](https://user-images.githubusercontent.com/22700499/216031042-cb802860-376a-427d-a7f1-2621a9a99095.png)

**Comment by jorio** [comment]
OK, new release coming soon with a fix for this

**Comment by jorio** [comment]
[Nanosaur 1.4.4](https://github.com/jorio/Nanosaur/releases/tag/v1.4.4) grants all your wishes ;)
