### ISSUE TITLE
Mac OSX (open nanosaur then press escape to start playing)

### ISSUE THREAD

**Issue by asa55** [jorio/Nanosaur#4]
Wife is so happy - she's been wanting to play this game again for years! Thanks for sharing this!

On Mac OSX, we downloaded the provided dmg file, opened, and it appeared "stuck" at a still image.

Pressing the escape key launches the game for us.

This is not an issue in need of resolution - just a comment for other users who might run into this. Feel free to close at your leisure.

(And thanks again)

**Comment by jorio** [comment]
Hi, glad this is making you guys happy!

When the game starts, it expects you to press Enter or Escape to get past the title card — it doesn't skip that screen automatically. I can look into making it more intuitive that the user must press something a key to skip that screen.

If you mean the game got stuck at a still image somewhere else though, then that's a bug I need to investigate!

**Comment by asa55** [comment]
Hi again - you hit it on the head - it's only pressing Enter or Escape at the title card we noticed. The game ran perfectly (and we've thoroughly tested to completion!)

**Comment by jorio** [comment]
v1.4.1 says "Hit space to continue" on these screens now :)
