### ISSUE TITLE
OpenGL Error When Launching The Game

### ISSUE THREAD

**Issue by BeauMarwaha** [jorio/Nanosaur#6]
Hello there,

First of all thanks so much for porting this game, looking forward to playing it again after all these years! After downloading and unzipping the latest release (1.4.1) of the game for windows I'm getting the following error:
![image](https://user-images.githubusercontent.com/3586073/103450106-799fb780-4c7f-11eb-8af8-847c514b0649.png)

My PC specs are as follows:
Operating System: Windows 10 Home 64-bit (10.0, Build 19041)
Language: English (Regional Setting: English)
System Manufacturer: Razer
System Model: Blade
BIOS: 1.02
Processor: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 CPUs), ~2.2GHz
Memory: 32768MB RAM
Page file: 18293MB used, 26660MB available
DirectX Version: DirectX 12
NVIDIA GeForce Driver: 460.89

**Comment by jorio** [comment]
Hi! I'm not able to investigate the Windows/Nvidia combo right now, but in the meantime, are you getting the same error with version 1.4.0? What's your graphics card model exactly?

**Comment by BeauMarwaha** [comment]
Just checked, I'm not getting the same error with version 1.4.0 (that version of the game appears to run perfectly fine). My specific graphics card version is the NVIDIA GeForce RTX 2070 with Max-Q Design.

**Comment by jorio** [comment]
[Version 1.4.2](https://github.com/jorio/Nanosaur/releases/tag/v1.4.2) just came out.  Does it run better for you?

**Comment by BeauMarwaha** [comment]
Just checked and yup the game now launches and runs successfully for me, thanks!
