### ISSUE TITLE
Can't find a way to message you.. So just putting it here for now.

### ISSUE THREAD

**Issue by macethetemplar** [jorio/Nanosaur#7]
First off I wanted to thank you for porting Nanosaur and Bugdom! As of right now I have played a few hours on both and have had no issues (OS 11.0.1). I have almost every year/make of Apple with every software combination at my disposal so if at any point you need it tested on hardware you do not have there is a chance that I do.

I was just emailing with Pangea to try and get the source for Power Pete / Mighty Mike but they said you already had it and redirected me here. Really looking forward to that port! I have the original CD with Art, Disc Case Art, and Official Strategy Guide that I can scan if you would like. Also everything that came on the original disc including other game demos and of course the original powerpete.sit file. It would be very cool to have the version running that says Power Pete and not Mighty Mike or to be able to choose which we start.

Thank you again! 
Mason
mason@larocka.org

MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
2.3 GHz Dual-Core Intel Core i5
8 GB 2133 MHz LPDDR3
Intel Iris Plus Graphics 640 1536 MB

**Comment by jorio** [comment]
Hi Mason, I sent you an email. Thanks!

**Comment by geocine** [comment]
Are you planning on a port of Power Pete / Mighty Mike @jorio

**Comment by jorio** [comment]
Yes - it's in progress ;)

**Comment by geocine** [comment]
I don't know if you have a Paypal @jorio  but I sent some amount using your email here in Github. Thank you for your work!

**Comment by jorio** [comment]
Thank you @geocine, your kind gesture made my day! Mighty Mike is almost ready and I plan to release it in the coming days.

**Comment by eisnerguy1** [comment]
> Thank you @geocine, your kind gesture made my day! Mighty Mike is almost ready and I plan to release it in the coming days.

<img src="https://media.giphy.com/media/f3jZ8moRBbEvNJjOtu/giphy.gif">

I'd be suuuuper happy to test that out 👍
